spring:
  datasource:
    url: mariadb://121.138.197.12:4021/a1?autoReconnect=true
    username: root
    password: springbatch!!!!
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #show_sql: true
        format_sql: true

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  mail:
    host: smtp.gmail.com
    port: 587
    username: ssk@codeum.tech
    password: qowmrdhqqlomcrjc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

logging.level:
  org.hibernate.SQL: debug
  #org.hibernate.type: trace